# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  # - 3.5
  # - 3.4
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
L    
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U tox-travis
  - pip install -r requirements.txt
  - pip install ".[test]" . # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage

# Command to run tests, e.g. python setup.py test
# script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: santoshphilip
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: pyenergyplus/eppy3000
#     python: 3.6
